[font]
size = 16.0
normal = { family = "Inconsolata Nerd Font Mono", style = "Regular" }

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.9
dynamic_title = true

[colors.primary]
background = "#1A1B26"
foreground = "#C0CAF5"

[colors.cursor]
cursor = "#787c99"

[colors.selection]
text = "#C0CAF5"
background = "#283457"

[colors.normal]
black = '#15161E'
red = '#F7768E'
green = '#9ECE6A'
yellow = '#E0AF68'
blue = '#7AA2F7'
magenta = '#BB9AF7'
cyan = '#7DCFFF'
white = '#A9B1D6'

[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'
