unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind ` popup 

bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded!"


set -g status-style fg="#7aa2f7",bg="#1a1b26"
set -g message-style fg="#7aa2f7",bg="#1a1b26"
set -g mode-style bg="#bb9af7",fg="#1a1b26"
set -g menu-selected-style bg="#bb9af7",fg="#1a1b26"
set -g status-left ""
set -g status-right " #[bg="#7aa2f7",fg="#1a1b26"]  #{session_name} #[normal]" 

set -g pane-border-lines "heavy"
set -g pane-border-style "fg=#7aa2f7"
set -g pane-active-border-style "fg=#bb9af7"
set -g pane-border-status off
set -g pane-border-format ""

set-window-option -g window-status-format "   #I: #W#F "
set-window-option -g window-status-style "bg=#1a1b26,fg=#7aa2f7"
set-window-option -g window-status-current-format "   #I: #W#F "
set-window-option -g window-status-current-style "fg=#1a1b26,bg=#7aa2f7,bold"

set -g status 2
set -g status-format[1] ""

set -g base-index 1
set-window-option -g pane-base-index 1
set -g mouse on
set -g focus-events on
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-*:RGB" # For true color support
set -g status-position top

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set -s copy-command 'wl-copy'
bind -n MouseDown2Pane run "tmux set-buffer -b primary_selection \"$(wl-paste -p)\"; tmux paste-buffer -b primary_selection; tmux delete-buffer -b primary_selection"
