name = "main"
position = "top"
layer = "bottom"
height = 48
exclusive_zone = true
#autohide = 2000

[ironvar_defaults]
network = "󰖪 Off"
bluetooth = "󰂲 Off"
sound = " 0%"

[[bar]]

[[start]]
type = "workspaces"

[[start]]
type = "launcher"
favourites = ["firefox", "steam", "1password"]

[[center]]
type = "music"
format = " {title} - {album} / {artist}" 

[[end]]
type = "custom"
class = "network"     

[[end.bar]]
type = "button"
label = "#network"  
on_click = "! ~/.config/waybar/scripts/start-or-focus.sh ~/.cargo/bin/impala"

[[end]]
type = "custom"
class = "bluetooth"     

[[end.bar]]
type = "button"
label = "#bluetooth"
on_click = "! ~/.config/waybar/scripts/start-or-focus.sh ~/.cargo/bin/bluetui"

[[end]]
type = "custom"
class = "sound"

[[end.bar]]
type = "button"
label = "#sound"
on_click = "! ~/.config/waybar/scripts/start-or-focus.sh wiremix"

[[end]]
type = "clock"
format = "%a %d %b %H:%M:%S"

[[end]]
type = "custom"
class = "power"

[[end.bar]]
type = "button"
label = ""
on_click = "! walker -nm menus:power --height 400"
