name = "power"
name_pretty = "Power"

[[entries]]
text = "Lock"
icon = ""
actions = { "lock" = "hyprlock" }

[[entries]]
text = "Suspend"
icon = ""
actions = { "suspend" = "systemctl suspend" }

[[entries]]
text = "Logout"
icon = "󰍃"
actions = { "logout" = "niri msg action quit -s" }

[[entries]]
text = "Reboot"
icon = ""
actions = { "reboot" = "systemctl reboot" }

[[entries]]
text = "Shutdown"
icon = "󰐥"
actions = { "shutdown" = "systemctl poweroff" }
