unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

set -g mouse on
set -g automatic-rename on
set -g automatic-rename-format '#{b:pane_current_path}'
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-*:RGB" # For true color support
set -g status-position top

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin "janoamaral/tokyo-night-tmux"

set -s copy-command 'wl-copy'
bind -n MouseDown2Pane run "tmux set-buffer -b primary_selection \"$(wl-paste -p)\"; tmux paste-buffer -b primary_selection; tmux delete-buffer -b primary_selection"

run '~/.tmux/plugins/tpm/tpm'
